services:
  # ============================================================
  # container_sindicato_18
  # ============================================================
  container_sindicato_18:
    image: odoo:18.0
    container_name: container_sindicato_18
    restart: unless-stopped

    environment:
      HOST: container_postgres_16
      USER: odoo
      PASSWORD: odoo

    networks:
      - postgres_16_network

    volumes:
      - ~/docker/container_sindicato_18/addons:/mnt/extra-addons
      - ~/docker/container_sindicato_18/config:/etc/odoo
      

    ports:
      - "8008:8008"
      - "8018:8069"
      - "8872:8072"
    command:
      - odoo
      - --db_host=container_postgres_16
      - --db_port=5432
      - --db_user=odoo
      - --db_password=odoo
      - --gevent-port=8072
    
      #- --database=container_sindicato_18
      #- --init=instance_sindicato
      #- --update=instance_sindicato
      - --without-demo=all


networks:
  postgres_16_network:
    external: true